---
server:
  port: 0
spring:
  application:
    name: "Spring Boot Template Web App"
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;Mode=Oracle
    driverClassName: org.h2.Driver
  liquibase:
    enabled: true
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        service-id: configserver
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
  instance:
    prefer-ip-address: false