---
server:
  port: 8080
spring:
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: false  
  jpa:
    properties:
      hibernate.format_sql: true
  application:
    name: "@project.artifactId@"
  datasource:
    generate-unique-name: false
    name: jb303
  inetutils:
    ignoredInterfaces:
      - docker0
      - veth.*
      - eth0
  config:
    import: "optional:configserver:"
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
      failFast: false
      discovery:
        service-id: spring-cloud-crud
        enabled: false        
eureka:
  instance:
    hostname: ${HOSTNAME}.columbus.local
    instanceId: "@project.artifactId@:${random.int[1,9]}"
gg:
  jte:
    use-precompiled-templates: true
app:
  page-title: "Useful Developer Resources"
  links:
    - name: "Home Page"
      url: "/"
    - name: "Swagger UI"
      url: "/swagger-ui/index.html"
    - name: "Actuator"
      url: "/actuator"
    - name: "H2 Console"
      url: "/h2-console"
    - name: "Catch View"
      url: "/catchview"
logging:
  level:
    "org.hibernate.SQL": "INFO"