server:
  port: 8080
spring:
  application:
    name: "@project.artifactId@"
  config:
    import: "optional:configserver:"
  main:
    web-application-type: reactive
  cloud:
    config:
      discovery:
        service-id: configserver
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: "@project.artifactId@:${random.int[1,9]}"
