<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>4.0.8</version>
    <!-- lookup parent from repository -->
  </parent>
  <modules>
    <module>spring-cloud-maven-deploy</module>
    <module>spring-cloud-gateway</module>
    <module>spring-cloud-config</module>
    <module>spring-cloud-demo-app</module>
    <module>spring-cloud-admin</module>
    <module>spring-cloud-initializr</module>
    <module>spring-cloud-service-discovery</module>
    <module>spring-cloud-feign-client</module>
    <module>spring-cloud-httpbin</module>
    <module>spring-cloud-liquibase</module>
    <module>spring-cloud-jte</module>
    <module>spring-cloud-crud</module>
    <module>spring-cloud-rest</module>
    <module>spring-cloud-function</module>
  </modules>
  <groupId>uk.gov.hmrc</groupId>
  <artifactId>spring-cloud-parent</artifactId>
  <version>0.6.0-SNAPSHOT</version>
  <name>spring-cloud-parent</name>
  <description>Spring Cloud Parent project for Spring Cloud Projects</description>
  <properties>
    <java.version>17</java.version>
    <spring-cloud.version>2025.1.3</spring-cloud.version>
    <maven-jar-plugin.version>3.2.0</maven-jar-plugin.version>
    <!-- Fixes Eclipse pom.xml error -->
    <project.build.outputTimestamp>2023-01-01T00:00:00Z</project.build.outputTimestamp>
    <maven.build.timestamp.format>yyyy-MM-dd-HH:mm</maven.build.timestamp.format>
    <gitflow-maven-plugin.version>1.16.0</gitflow-maven-plugin.version>
    <jib-maven-plugin.version>3.4.3</jib-maven-plugin.version>
    <spring-boot-admin.version>4.1.2</spring-boot-admin.version>
  </properties>
  <packaging>pom</packaging>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-config</artifactId>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-loadbalancer</artifactId>
    </dependency>
  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>de.codecentric</groupId>
        <artifactId>spring-boot-admin-dependencies</artifactId>
        <version>${spring-boot-admin.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-release-plugin</artifactId>
        <version>2.5</version>
      </plugin>
      <plugin>
        <groupId>io.github.git-commit-id</groupId>
        <artifactId>git-commit-id-maven-plugin</artifactId>
        <configuration>
          <generateGitPropertiesFile>true</generateGitPropertiesFile>
          <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties
            </generateGitPropertiesFilename>
          <commitIdGenerationMode>flat</commitIdGenerationMode>
          <includeOnlyProperties>
            <includeOnlyProperty>^git.branch$</includeOnlyProperty>
            <includeOnlyProperty>^git.build.(version)$</includeOnlyProperty>
            <includeOnlyProperty>^git.commit.id.(abbrev)$</includeOnlyProperty>
            <includeOnlyProperty>^git.commit.time</includeOnlyProperty>
          </includeOnlyProperties>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>jib-maven-plugin</artifactId>
        <version>${jib-maven-plugin.version}</version>
        <configuration>
          <from>
            <image>${env.FROM}</image>
          </from>
          <to>
            <image>${env.SERVER_ID}${env.SERVER_FOLDER}${project.artifactId}:${project.version}</image>
          </to>
          <container>
            <user>nobody:nobody</user>
          </container>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.graalvm.buildtools</groupId>
        <artifactId>native-maven-plugin</artifactId>
        <configuration>
          <imageName>${project.name}-fast</imageName>
          <buildArgs>
            <buildArg>-Ob</buildArg>
          </buildArgs>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>build-info</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.amashchenko.maven.plugin</groupId>
        <artifactId>gitflow-maven-plugin</artifactId>
        <version>1.20.0</version>
        <configuration>
          <pushRemote>true</pushRemote>
          <skipTestProject>true</skipTestProject>
          <allowSnapshots>true</allowSnapshots>
          <updateOutputTimestamp>false</updateOutputTimestamp>
          <versionDigitToIncrement>1</versionDigitToIncrement>
          <hotfixVersionDigitToIncrement>2</hotfixVersionDigitToIncrement>
          <useSnapshotInHotfix>true</useSnapshotInHotfix>
          <useSnapshotInSupport>true</useSnapshotInSupport>
          <gitFlowConfig>
            <productionBranch>master</productionBranch>
            <developmentBranch>develop</developmentBranch>
            <featureBranchPrefix>feature/</featureBranchPrefix>
            <releaseBranchPrefix>release/</releaseBranchPrefix>
            <hotfixBranchPrefix>hotfix/</hotfixBranchPrefix>
            <supportBranchPrefix>support/</supportBranchPrefix>
            <versionTagPrefix/>
            <origin>origin</origin>
          </gitFlowConfig>
          <commitMessages>
            <tagReleaseMessage>${tagReleaseMessage}</tagReleaseMessage>
            <releaseFinishMessage>Updating to @{version} from ${project.version}</releaseFinishMessage>
            <releaseStartMessage>Releasing @{version}</releaseStartMessage>
            <hotfixStartMessage>Updating to @{version} from ${project.version}</hotfixStartMessage>
            <tagVersionUpdateMessage>${tagReleaseMessage}</tagVersionUpdateMessage>
            <versionUpdateMessage>Updating to @{version} from ${project.version}</versionUpdateMessage>
            <supportStartMessage>Updating to @{version} from ${project.version}</supportStartMessage>
          </commitMessages>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-site-plugin</artifactId>
        <version>4.0.0-M15</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.2.5</version>
        <dependencies>
          <dependency>
            <groupId>me.fabriciorby</groupId>
            <artifactId>maven-surefire-junit5-tree-reporter</artifactId>
            <version>1.1.0</version>
          </dependency>
        </dependencies>
        <configuration>
          <reportFormat>plain</reportFormat>
          <consoleOutputReporter>
            <disable>true</disable>
          </consoleOutputReporter>
          <statelessTestsetInfoReporter implementation="org.apache.maven.plugin.surefire.extensions.junit5.JUnit5StatelessTestsetInfoTreeReporterUnicode"/>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <distributionManagement>
    <repository>
      <id>artifactory-api-token</id>
      <name>releases</name>
      <url>${env.ARTIFACTORY_REPO_PROTOCOL}${env.ARTIFACTORY_HOSTNAME}${env.ARTIFACTORY_REPO_MAVEN}</url>
    </repository>
    <snapshotRepository>
      <id>artifactory-api-token</id>
      <name>snapshots</name>
      <url>${env.ARTIFACTORY_REPO_PROTOCOL}${env.ARTIFACTORY_HOSTNAME}${env.ARTIFACTORY_REPO_MAVEN}</url>
    </snapshotRepository>
  </distributionManagement>
</project>
