<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
	  <groupId>uk.gov.hmrc</groupId>	  	
	  <artifactId>spring-cloud-parent</artifactId>	  	
	  <version>0.6.0-SNAPSHOT</version>
	</parent>

	<artifactId>spring-cloud-feign-client</artifactId>
	<packaging>jar</packaging>
	<description>spring-cloud-feign-client</description>
	<name>spring-cloud-feign-client</name>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
    </dependencies>
</project>
