default:
  tags:
    - tenants-demo-nonprod
include:
  - project: 'cbi-hawk/platform/gitlab-common'
    ref: v1.3.11
    file: '/templates/gitlab/JavaDockerSocket.gitlab-ci.yml'

variables:
  DEPLOY_DEV: "false"
  CONFIG_BRANCH: master

## Specify a different jdk image for pipeline jobs if default not suitable
## Example:
## image: cbi-hawk-docker-virtual.artifactory.alm.corp.hmrc.gov.uk/maven:3.8-openjdk-11

deploy-dev:
  variables:
    STAGE: nonprod
    ENVIRONMENT: dev
    DOCKER_TAG: $CI_COMMIT_SHORT_SHA
    NAMESPACE: tenant-hawk-demo-dev
    DEPLOY_DEV: $DEPLOY_DEV
  stage: deploy
  trigger:
    project: 'cbi-hawk/tenants/demo/demo-app-config'
    branch: "${CONFIG_BRANCH}"
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $DEPLOY_DEV == "true"

deploy-qa:
  variables:
    STAGE: nonprod
    ENVIRONMENT: qa
    DOCKER_TAG: $CI_COMMIT_TAG
    NAMESPACE: tenant-hawk-demo-qa
  stage: deploy
  trigger:
    project: 'cbi-hawk/tenants/demo/demo-app-config'
    branch: master
  rules:
    - if: '$DEPLOY_CIT == "true" || $DEPLOY_PVT == "true" || $DEPLOY_OAT == "true" || $DEPLOY_SIT == "true" || $DEPLOY_PREPROD == "true" || $DEPLOY_PROD == "true"'
      when: never
    - if: $CI_COMMIT_TAG =~ /^RC.*/
    - if: ($DEPLOY_QA == "true" && $CI_COMMIT_TAG =~ /^(\d+\.)?(\d+\.)?(\*|\d+)$/)

deploy-cit:
  variables:
    STAGE: nonprod
    ENVIRONMENT: cit
    DOCKER_TAG: $CI_COMMIT_TAG
    NAMESPACE: tenant-hawk-demo-cit
  stage: deploy
  trigger:
    project: 'cbi-hawk/tenants/demo/demo-app-config'
    branch: master
  rules:
    - if: ($DEPLOY_CIT == "true" && ($CI_COMMIT_TAG =~ /^(\d+\.)?(\d+\.)?(\*|\d+)$/ || $CI_COMMIT_TAG =~ /^RC.*/))

deploy-sit:
  variables:
    STAGE: nonprod
    ENVIRONMENT: sit
    DOCKER_TAG: $CI_COMMIT_TAG
    NAMESPACE: tenant-hawk-demo-sit
  stage: deploy
  trigger:
    project: 'cbi-hawk/tenants/demo/demo-app-config'
    branch: master
  rules:
    - if: ($DEPLOY_SIT == "true" && ($CI_COMMIT_TAG =~ /^(\d+\.)?(\d+\.)?(\*|\d+)$/ || $CI_COMMIT_TAG =~ /^RC.*/))

deploy-pvt:
  variables:
    STAGE: poat
    ENVIRONMENT: pvt
    DOCKER_TAG: $CI_COMMIT_TAG
    NAMESPACE: tenant-hawk-demo-pvt
  stage: deploy
  trigger:
    project: 'cbi-hawk/tenants/demo/demo-app-config'
    branch: master
  rules:
    - if: ($DEPLOY_PVT == "true" && ($CI_COMMIT_TAG =~ /^(\d+\.)?(\d+\.)?(\*|\d+)$/ || $CI_COMMIT_TAG =~ /^RC.*/))

deploy-oat:
  variables:
    STAGE: poat
    ENVIRONMENT: oat
    DOCKER_TAG: $CI_COMMIT_TAG
    NAMESPACE: tenant-hawk-demo-oat
  stage: deploy
  trigger:
    project: 'cbi-hawk/tenants/demo/demo-app-config'
    branch: master
  rules:
    - if: ($DEPLOY_OAT == "true" && ($CI_COMMIT_TAG =~ /^(\d+\.)?(\d+\.)?(\*|\d+)$/ || $CI_COMMIT_TAG =~ /^RC.*/))

deploy-preprod:
  variables:
    STAGE: preprod
    ENVIRONMENT: preprod
    DOCKER_TAG: $CI_COMMIT_TAG
    NAMESPACE: tenant-hawk-demo-preprod
  stage: deploy
  trigger:
    project: 'cbi-hawk/tenants/demo/demo-app-config'
    branch: master
  rules:
    - if: ($DEPLOY_PREPROD == "true" && $CI_COMMIT_TAG =~ /^(\d+\.)?(\d+\.)?(\*|\d+)$/)

deploy-prod:
  variables:
    STAGE: prod
    ENVIRONMENT: prod
    DOCKER_TAG: $CI_COMMIT_TAG
    NAMESPACE: tenant-hawk-demo-prod
  stage: deploy
  trigger:
    project: 'cbi-hawk/tenants/demo/demo-app-config'
    branch: master
  rules:
    - if: ($DEPLOY_PROD == "true" && $CI_COMMIT_TAG =~ /^(\d+\.)?(\d+\.)?(\*|\d+)$/)
