management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
    shutdown:
      enabled: true
    restart:
      enabled: true
    pause:
      enabled: true
    refresh: 
      enabled: true
    resume:
      enabled: true
  info:
    java:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
info:
  app:
    hostname: ${spring.cloud.client.hostname}
    port: ${local.server.port}