server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: ${HOSTNAME}.columbus.local
    instanceId: "@project.artifactId@:${random.int[1,99]}"
spring:
  config:
    import: "optional:configserver:"
  cloud:
    discovery:
      enabled: false
    config:
      failFast: false
      discovery:
        service-id: spring-cloud-initializr
        enabled: false
  application:
    name: "@project.artifactId@"
