---
server:
  port: 8084
spring:
  application:
    name: "Spring Boot Template Web App"
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;Mode=Oracle
    driverClassName: org.h2.Driver
  liquibase:
    enabled: true
management:
  endpoints:
    web:
      base-path: "/manage"
      exposure:
        include: "*"
