spring:
  config:
    import: "optional:configserver:"
  application:
    name: "@project.artifactId@"
server:
  port: 8761
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    preferIpAddress: false
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
