spring.application.name=spring-web-standalone
server.server-header=
management.endpoints.web.exposure.exclude=*
server.error.include-stacktrace=never
server.error.whitelabel.enabled=false
server.error.include-message=false
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.prefix=stdout
server.tomcat.accesslog.directory=/dev
server.tomcat.accesslog.suffix=
server.tomcat.accesslog.rotate=false
server.tomcat.accesslog.pattern=common