spring:
  application:
    name: "@project.artifactId@"
  liquibase:
    user: hawk_admin
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    change-log: classpath:/db/changelog/db.changelog-debug.yaml
  datasource:
    url: jdbc:mysql://emcs-dev-rds-mysql.climtqmwjchm.eu-west-2.rds.amazonaws.com:3306/emcs?autoReconnect=true&useSSL=true&requireSSL=true&clientCertificateKeyStoreUrl=file:src/main/resources/HMRC-trustStore.p12&clientCertificateKeyStorePassword=changeit
    user: hawk_admin
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    maximum-pool-size: 2
    driverClassName: com.mysql.cj.jdbc.Driver
  config:
    import: "optional:configserver:"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration