server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
          order: 1
