server:
  port: 0
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
          order: 1
      discovery:
        enabled: true
        service-id: "@project.artifactId@"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: "@project.artifactId@:${random.int[1,9]}"
