<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>uk.gov.hmrc</groupId>
    <artifactId>spring-cloud-parent</artifactId>
    <version>0.6.0-SNAPSHOT</version>
  </parent>
  <groupId>uk.gov.hmrc</groupId>
  <artifactId>spring-cloud-initializr</artifactId>
  <version>0.6.0-SNAPSHOT</version>
  <name>spring-cloud-initializr</name>
  <description>Demo project for Spring Cloud Initializr</description>
  <properties>
    <java.version>17</java.version>
    <jib-maven-plugin.version>3.4.0</jib-maven-plugin.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>io.spring.initializr</groupId>
      <artifactId>initializr-web</artifactId>
    </dependency>
    <dependency>
      <groupId>io.spring.initializr</groupId>
      <artifactId>initializr-generator-spring</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-config</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.spring.initializr</groupId>
        <artifactId>initializr-bom</artifactId>
        <version>0.23.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-release-plugin</artifactId>
        <version>2.5</version>
      </plugin>
      <plugin>
        <groupId>io.github.git-commit-id</groupId>
        <artifactId>git-commit-id-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>build-info</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>jib-maven-plugin</artifactId>
        <version>${jib-maven-plugin.version}</version>
        <configuration>
          <from>
            <image>${env.FROM}</image>
          </from>
          <to>
            <image>${env.ARTIFACTORY_REPO}.${env.ARTIFACTORY_HOSTNAME}${env.SERVER_FOLDER}${project.artifactId}:${project.version}</image>
          </to>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <distributionManagement>
    <repository>
      <id>artifactory-api-token</id>
      <name>releases</name>
      <url>${env.ARTIFACTORY_REPO_PROTOCOL}${env.ARTIFACTORY_HOSTNAME}${env.ARTIFACTORY_REPO_MAVEN}</url>
    </repository>
    <snapshotRepository>
      <id>artifactory-api-token</id>
      <name>snapshots</name>
      <url>${env.ARTIFACTORY_REPO_PROTOCOL}${env.ARTIFACTORY_HOSTNAME}${env.ARTIFACTORY_REPO_MAVEN}</url>
    </snapshotRepository>
  </distributionManagement>
</project>
